### ISSUE TITLE
Test support for copy and paste in the field

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/tabto#5]
When I paste something which is longer or equal the maxLength, I should jump to the next field.

**Comment by marlass** [comment]
Hope my PR will help with this issue.
Apart from that issue I recommend outputing also this library to format that can be consumed directly in browser. With that it can be used by more folks and it won't require advanced build tools.

**Comment by damienalexandre** [comment]
Thank you for your PR. 

About your second point, do you have an idea of what we should do? Like a jQuery plugin integration or something like that?

**Comment by marlass** [comment]
I wouldn't go that far. The only thing that now makes it impossible to run in the browser is "module.exports" syntax. Would be good to compile it to "umd" format. It would then be available in global scope and can be directly consumed (by example from unpkg). I can help you with that. If you could just create an issue for it and I will work on that tomorrow.

**Comment by damienalexandre** [comment]
Awesome, sound good to me.

I created the issue here: https://github.com/jolicode/tabto/issues/13
